[theme]
base = "light"
primaryColor = "#FF1E1E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#DCDCDD"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false